name: efitools
summary: EFI tools
description: |
  EFI tools
version: 1.9.2-3ubuntu3
base: core24
confinement: strict

apps:
  tool:
    command: bin/cmd
    plugs:
      - fwupd
      - hardware-observe

parts:
  efitools:
    plugin: nil
    stage-packages:
      - efitools

  snap-files:
    plugin: dump
    source: .
