#!/bin/bash


show_help() {
    echo "usage: $(basename "$0") [<port>] [<user>]"
}

case "$1" in
    -h|--help)
        show_help 2>&1
        exit 0
        ;;
esac

set -xue
port="${1:-}"
user="${2:-guest}"

if ! test -n "$port" ; then
    echo "port unset"; exit 1
fi

ssh-unsafe -p "$port" "$user"@localhost "mkdir -p ~/snapd"
rsync -avz \
    --exclude .image-garden/ \
    -e "ssh-unsafe -p $port" \
    . "$user"@localhost:~/snapd/
